import type { Metadata } from 'next';
import { Nanum_Myeongjo } from 'next/font/google';
import './globals.css';

const nanumMyeongjo = Nanum_Myeongjo({
  subsets: ['latin'],
  weight: ['400', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='ko'>
      <body className={nanumMyeongjo.className}>{children}</body>
    </html>
  );
}
